---
# handlers file for web
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: restart php
  systemd:
    name: php-fpm.service 
    state: restarted
    enabled: yes